package julianh06.wynnextras.wynncraft.menu;

public enum MenuType {
    NONE,
    UNKNOWN,
    ACCOUNT_BANK,
    CHARACTER_BANK,
    MISC_BUCKET,
    BOOKSHELF,
    CRAFTING_STATION,
    CHARACTER_INFO,
    TOME,
    CLASS_SELECTION,
    ITEM_IDENTIFIER,
    AUGMENT_IDENTIFIER,
    POWDER_MASTER_REMOVE,
    POWDER_MASTER_COMBINE,
    ITEM_UPGRADER,
    ITEM_UPGRADER_COMBINE,
    TRADE_MARKET,
    PARTY_FINDER,
    RAID_REWARD,
    ABILITY_TREE
}
